### ISSUE TITLE
Installed packages are stored with priority 0 instead of source priority

### ISSUE THREAD

**Issue by weberkai** [jaos/slapt-get#25]
Hi!

First, thanks for your work, it's great.

I think i've found an error.

I've added these two repositories:
SOURCE=https://ponce.cc/slackware/slackware64-15.0/packages/:CUSTOM
SOURCE=https://slackware.uk/people/alien/sbrepos/15.0/x86_64/:CUSTOM

I can see their priority is 6.

Then I've installed xvidcore from ponce repository.

When I ask to upgrade all packages, xvidcore is marked for upgrade, but I think this is wrong, look at their versions:
1.3.7-x86_64-1ponce
1.3.7-x86_64-1alien

I can see the priority of all installed packages changed to 0, which is causing wrong comparison. I think after I install xvidcore it should keep his priority 6, so the comparison would return they are the same version.

Please, can you look at it?

Thanks you very much.

**Comment by jaos** [comment]
The priority is only applied to your package sources, with installed packages having a zero priority because we lose that information in the installation metadata. 

Since you have Ponce and alien both providing that package you should chose which repository gets the custom priority over preferred. 


take care,
Jason

**Comment by weberkai** [comment]
Hi!
Thanks for such a fast reply.
I'll close this issue then, as this is not a bug.
I have more than 4 repositories, so I'll have to dig in further to solve how to fit them all in these 4 available levels of priority.
Thanks.
Best regards.
